
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { BusinessPartner } from "@/types/businessPartner";

export type BusinessPartnerInput = {
  bp_name: string;
  contact_person: string;
  phone_country?: string | null;
  phone_number?: string | null;
  email?: string | null;
  address?: string | null;
  country?: string | null;
  payment_terms: string;
  payment_method?: string | null;
  bp_type?: string | null;
  material_1?: string | null;
  material_2?: string | null;
  material_3?: string | null;
  communication_method?: string | null;
  shipping_method?: string | null;
};

export const createBusinessPartner = async (data: BusinessPartnerInput): Promise<BusinessPartner | null> => {
  try {
    console.log("Creating business partner with data:", data);
    
    // Use the "upsert" method with "onConflict" to handle potential conflicts better
    // We need to use 'as any' to bypass the type check since bp_code is generated by a database trigger
    const { data: newPartner, error } = await supabase
      .from('business_partners')
      .insert(data as any)
      .select();

    if (error) {
      if (error.message.includes('statement timeout')) {
        console.log("Timeout error, checking if the business partner was created");
        // Even though we got a timeout, the operation might have succeeded
        // Let's check if the business partner was actually created
        const { data: checkPartner } = await supabase
          .from('business_partners')
          .select()
          .match({ 
            bp_name: data.bp_name, 
            contact_person: data.contact_person,
            email: data.email 
          })
          .order('created_at', { ascending: false })
          .limit(1);
        
        if (checkPartner && checkPartner.length > 0) {
          console.log("Business Partner was created despite timeout:", checkPartner[0]);
          toast.success('Business Partner created successfully');
          return checkPartner[0];
        }
        
        console.error("Business Partner creation failed after timeout check", error);
        toast.error('Request timed out. Please try again.');
      } else if (error.message.includes('duplicate key')) {
        console.error("Duplicate key error:", error);
        toast.error('A business partner with this code already exists.');
      } else {
        console.error("Other database error:", error);
        toast.error(`Error creating business partner: ${error.message}`);
      }
      console.error('Supabase error:', error);
      return null;
    }
    
    console.log("Business Partner created successfully:", newPartner);
    toast.success('Business Partner created successfully');
    return Array.isArray(newPartner) ? newPartner[0] : newPartner;
  } catch (error: any) {
    console.error('Unexpected error:', error);
    toast.error(`Error creating business partner: ${error.message || 'Unknown error'}`);
    return null;
  }
};

export const getBusinessPartners = async (): Promise<BusinessPartner[]> => {
  try {
    console.log("Fetching business partners");
    const { data, error } = await supabase
      .from('business_partners')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      if (error.message.includes('statement timeout')) {
        console.error("Timeout error fetching business partners:", error);
        toast.error('Request timed out while fetching business partners.');
      } else {
        console.error("Error fetching business partners:", error);
        toast.error(`Error fetching business partners: ${error.message}`);
      }
      console.error('Supabase error:', error);
      return [];
    }
    
    console.log("Fetched business partners:", data?.length || 0);
    return data || [];
  } catch (error: any) {
    console.error('Unexpected error:', error);
    toast.error(`Error fetching business partners: ${error.message || 'Unknown error'}`);
    return [];
  }
};
