// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckbwmjcydbvbuasbjgcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrYndtamN5ZGJ2YnVhc2JqZ2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjI2NTIsImV4cCI6MjA1OTA5ODY1Mn0.svzezlCKqZk3yiflxGxBXS7ApUQgF8SmZhr5ZPF0f0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);